### ISSUE TITLE
mb_lang not supported

### ISSUE THREAD

**Issue by carry2web** [gordon-matt/peachpie-responsive-file-manager#18] opened 2020-09-28 10:25 UTC
I got this testing responsive file manager with peach pie and switching language via the globe icon:

Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/2.0 POST https://localhost:44317/filemanager/ajax_calls.php?action=get_lang  0
PHP (Warning): Function 'mb_language' is not supported
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 125.1492ms 200 text/html; charset=UTF-8
Exception thrown: 'Pchp.Core.ScriptDiedException' in ResponsiveFileManager.dll
An exception of type 'Pchp.Core.ScriptDiedException' occurred in ResponsiveFileManager.dll but was not handled in user code

Is this caused by peachpie not having mb_language implemented or am I missing something locally?

**Comment by jakubmisek** [comment] 2020-09-28 14:33
`mb_language` shows the warning, but it has no effect on the application. (It only affects sending emails, which is not even needed for responsive file manager. I'm not sure why the author of responsive file manager put it there.)

`ScriptDiedException` (https://docs.peachpie.io/api/ref/scriptdiedexception/) is usually a handled by-design exception. Does it crash the application, or is it just handled by Visual Studio debugger and the application continues?

**Comment by jakubmisek** [comment] 2020-09-28 15:02
Seems the `exit()` in source code (causing ScriptDieException) can be ignored.

Anyways there was no list of languages when clicking on globe icon; it is caused by peachpie (https://github.com/peachpiecompiler/peachpie/issues/850), will be fixed in the next update

**Comment by jakubmisek** [comment] 2020-09-28 15:05
with the issue fixed, the languges are listed as below

![image](https://user-images.githubusercontent.com/842150/94449749-bc4b8280-01ac-11eb-85bd-b7d3a34af6a7.png)

thanks for reporting the issue!

**Comment by gordon-matt** [comment] 2020-09-29 00:01
Thanks @jakubmisek . I have just merged PR #16 . I won't release it yet though.. I think its best to wait for you to either raise another PR with the new PeachPie referenced or update me here when its available and I will do so myself. Then I will release the new NuGet packages.

**Comment by jakubmisek** [comment] 2020-09-29 11:36
@gordon-matt thanks, the next update will be in a few days

**Closed as completed** 2020-10-30 00:45 UTC
